### PR TITLE
Add MPI Sessions hello world

### PR DESCRIPTION
**Pull request by mathomp4**
This is my attempt to add a hello world example using MPI Sessions. I was inspired by the Open MPI BoF at SC23. Note that this is *shamelessly* based on `sessions_ex3.f90` from https://github.com/open-mpi/ompi-tests-public/tree/master/sessions by @hppritcha

When run you get:
```
Compiler Version: GCC version 12.3.0
MPI Version: 3.1
MPI Library Version: Open MPI v5.0.0, package: Open MPI mathomp4@gs6101-Dagobah.ndc.nasa.gov Distribution, ident: 5.0.0, repo rev: v5.0.0, Oct 26, 2023
 Pset            0  name: mpi://WORLD
 Pset            1  name: mpi://SELF
 Pset            2  name: mpix://SHARED
Process    0 of    4 is on gs6101-Dagobah.ndc.nasa.gov
Process    1 of    4 is on gs6101-Dagobah.ndc.nasa.gov
Process    3 of    4 is on gs6101-Dagobah.ndc.nasa.gov
Process    2 of    4 is on gs6101-Dagobah.ndc.nasa.gov
```

---

Note, a couple oddities. First, in the code I have:
```fortran
   character(len=MPI_MAX_PSET_NAME_LEN), allocatable :: pset_names(:), dummy
...
   allocate(pset_names(0:n_psets-1))
   do i = 0, n_psets-1
      pset_names(i) = ""
      call MPI_Session_get_nth_pset(shandle, MPI_INFO_NULL, i, pset_len(i), pset_names(i))
   end do
...
   if (myid == 0) then
      ! Now let's print out the array of pset names just because I'm not sure what they are...
      do i = 0, n_psets-1
         write(*,*) "Pset ", i, " name: ", trim(pset_names(i))
      end do
   end if
```

which gets the good output above.

My first attempt I didn't have:
```fortran
      pset_names(i) = ""
```
to initialize the array to "", and that output garbage despite the trim in the write:
```
Compiler Version: GCC version 12.3.0
MPI Version: 3.1
MPI Library Version: Open MPI v5.0.0, package: Open MPI mathomp4@gs6101-Dagobah.ndc.nasa.gov Distribution, ident: 5.0.0, repo rev: v5.0.0, Oct 26, 2023
 Pset            0  name: mpi://WORLD � ZTUM����������������ZTUMZTUM�lp��`�pkd<���������:;p�ZTUM� ZTUM��������O�������ZTUMZTUMDNOC
 Pset            1  name: mpi://SELF (�X��G�o�������ox�
 Pset            2  name: mpix://SHARED �g<�g<
Process    0 of    4 is on gs6101-Dagobah.ndc.nasa.gov
Process    1 of    4 is on gs6101-Dagobah.ndc.nasa.gov
Process    2 of    4 is on gs6101-Dagobah.ndc.nasa.gov
Process    3 of    4 is on gs6101-Dagobah.ndc.nasa.gov
```
Now, this might be a feature/bug/🤷🏼 of the how Fortran gets the name via C? Not sure, but it seems to indicate that it's not whitespace in the buffer, but uninitialized.

Next, I tried to be clever and tried:
```fortran
   allocate(pset_names(0:n_psets-1), source="")
```
but that didn't seem to work either:
```
Compiler Version: GCC version 12.3.0
MPI Version: 3.1
MPI Library Version: Open MPI v5.0.0, package: Open MPI mathomp4@gs6101-Dagobah.ndc.nasa.gov Distribution, ident: 5.0.0, repo rev: v5.0.0, Oct 26, 2023
��F�(�           0  name: mpi://WORLD �F�(�
 Pset            1  name: mpi://SELF
 Pset            2  name: mpix://SHARED
Process    0 of    4 is on gs6101-Dagobah.ndc.nasa.gov
Process    1 of    4 is on gs6101-Dagobah.ndc.nasa.gov
Process    3 of    4 is on gs6101-Dagobah.ndc.nasa.gov
Process    2 of    4 is on gs6101-Dagobah.ndc.nasa.gov
```
I might need to impose on @tclune to educate me on that. I sort of assumed:
```fortran
   allocate(pset_names(0:n_psets-1), source="")
```
would be equivalent to:
```fortran
   allocate(pset_names(0:n_psets-1))
   do i = 0, n_psets-1
      pset_names(i) = ""
   end do
```
but it doesn't seem like it?

### CODE REVIEW

**Comment by hppritcha** [comment]
Hi Matt,

Okay thanks for checking this.  I’ll open an issue and get a fix in for 5.0.1!

Howard

From: Matthew Thompson ***@***.***>
Reply-To: mathomp4/MPITests ***@***.***>
Date: Wednesday, November 15, 2023 at 6:24 PM
To: mathomp4/MPITests ***@***.***>
Cc: "Pritchard Jr., Howard" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] [mathomp4/MPITests] Add MPI Sessions hello world (PR #1)


This is my attempt to add a hello world example using MPI Sessions. I was inspired by the Open MPI BoF at SC23. Note that this is shamelessly based on sessions_ex3.f90 from https://github.com/open-mpi/ompi-tests-public/tree/master/sessions<https://urldefense.com/v3/__https:/github.com/open-mpi/ompi-tests-public/tree/master/sessions__;!!Bt8fGhp8LhKGRg!FwjK_Ds1tz4dAuHmk29pOSa3ScWBs882LDV0xbcBrQTlcsINGHrZBTPFhmXe9KpaWHUZ_kr_PsoemhrdXJlsz4j3$> by @hppritcha<https://urldefense.com/v3/__https:/github.com/hppritcha__;!!Bt8fGhp8LhKGRg!FwjK_Ds1tz4dAuHmk29pOSa3ScWBs882LDV0xbcBrQTlcsINGHrZBTPFhmXe9KpaWHUZ_kr_PsoemhrdXF2dOAzs$>

When run you get:

Compiler Version: GCC version 12.3.0

MPI Version: 3.1

MPI Library Version: Open MPI v5.0.0, package: Open MPI ***@***.*** Distribution, ident: 5.0.0, repo rev: v5.0.0, Oct 26, 2023

 Pset            0  name: mpi://WORLD

 Pset            1  name: mpi://SELF

 Pset            2  name: mpix://SHARED

Process    0 of    4 is on gs6101-Dagobah.ndc.nasa.gov<https://urldefense.com/v3/__http:/gs6101-Dagobah.ndc.nasa.gov__;!!Bt8fGhp8LhKGRg!FwjK_Ds1tz4dAuHmk29pOSa3ScWBs882LDV0xbcBrQTlcsINGHrZBTPFhmXe9KpaWHUZ_kr_PsoemhrdXIdGwtIg$>

Process    1 of    4 is on gs6101-Dagobah.ndc.nasa.gov<https://urldefense.com/v3/__http:/gs6101-Dagobah.ndc.nasa.gov__;!!Bt8fGhp8LhKGRg!FwjK_Ds1tz4dAuHmk29pOSa3ScWBs882LDV0xbcBrQTlcsINGHrZBTPFhmXe9KpaWHUZ_kr_PsoemhrdXIdGwtIg$>

Process    3 of    4 is on gs6101-Dagobah.ndc.nasa.gov<https://urldefense.com/v3/__http:/gs6101-Dagobah.ndc.nasa.gov__;!!Bt8fGhp8LhKGRg!FwjK_Ds1tz4dAuHmk29pOSa3ScWBs882LDV0xbcBrQTlcsINGHrZBTPFhmXe9KpaWHUZ_kr_PsoemhrdXIdGwtIg$>

Process    2 of    4 is on gs6101-Dagobah.ndc.nasa.gov<https://urldefense.com/v3/__http:/gs6101-Dagobah.ndc.nasa.gov__;!!Bt8fGhp8LhKGRg!FwjK_Ds1tz4dAuHmk29pOSa3ScWBs882LDV0xbcBrQTlcsINGHrZBTPFhmXe9KpaWHUZ_kr_PsoemhrdXIdGwtIg$>

________________________________

Note, a couple oddities. First, in the code I have:

   character(len=MPI_MAX_PSET_NAME_LEN), allocatable :: pset_names(:), dummy

...

   allocate(pset_names(0:n_psets-1))

   do i = 0, n_psets-1

      pset_names(i) = ""

      call MPI_Session_get_nth_pset(shandle, MPI_INFO_NULL, i, pset_len(i), pset_names(i))

   end do

...

   if (myid == 0) then

      ! Now let's print out the array of pset names just because I'm not sure what they are...

      do i = 0, n_psets-1

         write(*,*) "Pset ", i, " name: ", trim(pset_names(i))

      end do

   end if

which gets the good output above.

My first attempt I didn't have:

      pset_names(i) = ""

to initialize the array to "", and that output garbage despite the trim in the write:

Compiler Version: GCC version 12.3.0

MPI Version: 3.1

MPI Library Version: Open MPI v5.0.0, package: Open MPI ***@***.*** Distribution, ident: 5.0.0, repo rev: v5.0.0, Oct 26, 2023

 Pset            0  name: mpi://WORLD � ZTUM����������������ZTUMZTUM�lp��`�pkd<���������:;p�ZTUM� ZTUM��������O�������ZTUMZTUMDNOC

 Pset            1  name: mpi://SELF (�X��G�o�������ox�

 Pset            2  name: mpix://SHARED �g<�g<

Process    0 of    4 is on gs6101-Dagobah.ndc.nasa.gov<https://urldefense.com/v3/__http:/gs6101-Dagobah.ndc.nasa.gov__;!!Bt8fGhp8LhKGRg!FwjK_Ds1tz4dAuHmk29pOSa3ScWBs882LDV0xbcBrQTlcsINGHrZBTPFhmXe9KpaWHUZ_kr_PsoemhrdXIdGwtIg$>

Process    1 of    4 is on gs6101-Dagobah.ndc.nasa.gov<https://urldefense.com/v3/__http:/gs6101-Dagobah.ndc.nasa.gov__;!!Bt8fGhp8LhKGRg!FwjK_Ds1tz4dAuHmk29pOSa3ScWBs882LDV0xbcBrQTlcsINGHrZBTPFhmXe9KpaWHUZ_kr_PsoemhrdXIdGwtIg$>

Process    2 of    4 is on gs6101-Dagobah.ndc.nasa.gov<https://urldefense.com/v3/__http:/gs6101-Dagobah.ndc.nasa.gov__;!!Bt8fGhp8LhKGRg!FwjK_Ds1tz4dAuHmk29pOSa3ScWBs882LDV0xbcBrQTlcsINGHrZBTPFhmXe9KpaWHUZ_kr_PsoemhrdXIdGwtIg$>

Process    3 of    4 is on gs6101-Dagobah.ndc.nasa.gov<https://urldefense.com/v3/__http:/gs6101-Dagobah.ndc.nasa.gov__;!!Bt8fGhp8LhKGRg!FwjK_Ds1tz4dAuHmk29pOSa3ScWBs882LDV0xbcBrQTlcsINGHrZBTPFhmXe9KpaWHUZ_kr_PsoemhrdXIdGwtIg$>

Now, this might be a feature/bug/🤷🏼 of the how Fortran gets the name via C? Not sure, but it seems to indicate that it's not whitespace in the buffer, but uninitialized.

Next, I tried to be clever and tried:

   allocate(pset_names(0:n_psets-1), source="")

but that didn't seem to work either:

Compiler Version: GCC version 12.3.0

MPI Version: 3.1

MPI Library Version: Open MPI v5.0.0, package: Open MPI ***@***.*** Distribution, ident: 5.0.0, repo rev: v5.0.0, Oct 26, 2023

��F�(�           0  name: mpi://WORLD �F�(�

 Pset            1  name: mpi://SELF

 Pset            2  name: mpix://SHARED

Process    0 of    4 is on gs6101-Dagobah.ndc.nasa.gov<https://urldefense.com/v3/__http:/gs6101-Dagobah.ndc.nasa.gov__;!!Bt8fGhp8LhKGRg!FwjK_Ds1tz4dAuHmk29pOSa3ScWBs882LDV0xbcBrQTlcsINGHrZBTPFhmXe9KpaWHUZ_kr_PsoemhrdXIdGwtIg$>

Process    1 of    4 is on gs6101-Dagobah.ndc.nasa.gov<https://urldefense.com/v3/__http:/gs6101-Dagobah.ndc.nasa.gov__;!!Bt8fGhp8LhKGRg!FwjK_Ds1tz4dAuHmk29pOSa3ScWBs882LDV0xbcBrQTlcsINGHrZBTPFhmXe9KpaWHUZ_kr_PsoemhrdXIdGwtIg$>

Process    3 of    4 is on gs6101-Dagobah.ndc.nasa.gov<https://urldefense.com/v3/__http:/gs6101-Dagobah.ndc.nasa.gov__;!!Bt8fGhp8LhKGRg!FwjK_Ds1tz4dAuHmk29pOSa3ScWBs882LDV0xbcBrQTlcsINGHrZBTPFhmXe9KpaWHUZ_kr_PsoemhrdXIdGwtIg$>

Process    2 of    4 is on gs6101-Dagobah.ndc.nasa.gov<https://urldefense.com/v3/__http:/gs6101-Dagobah.ndc.nasa.gov__;!!Bt8fGhp8LhKGRg!FwjK_Ds1tz4dAuHmk29pOSa3ScWBs882LDV0xbcBrQTlcsINGHrZBTPFhmXe9KpaWHUZ_kr_PsoemhrdXIdGwtIg$>

I might need to impose on @tclune<https://urldefense.com/v3/__https:/github.com/tclune__;!!Bt8fGhp8LhKGRg!FwjK_Ds1tz4dAuHmk29pOSa3ScWBs882LDV0xbcBrQTlcsINGHrZBTPFhmXe9KpaWHUZ_kr_PsoemhrdXOe0PMHe$> to educate me on that. I sort of assumed:

   allocate(pset_names(0:n_psets-1), source="")

would be equivalent to:

   allocate(pset_names(0:n_psets-1))

   do i = 0, n_psets-1

      pset_names(i) = ""

   end do

but it doesn't seem like it?

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/mathomp4/MPITests/pull/1<https://urldefense.com/v3/__https:/github.com/mathomp4/MPITests/pull/1__;!!Bt8fGhp8LhKGRg!FwjK_Ds1tz4dAuHmk29pOSa3ScWBs882LDV0xbcBrQTlcsINGHrZBTPFhmXe9KpaWHUZ_kr_PsoemhrdXGw-t4Nm$>

Commit Summary

  *   d493451<https://urldefense.com/v3/__https:/github.com/mathomp4/MPITests/pull/1/commits/d493451d7ad57a501aa1152afa126760ce3defcc__;!!Bt8fGhp8LhKGRg!FwjK_Ds1tz4dAuHmk29pOSa3ScWBs882LDV0xbcBrQTlcsINGHrZBTPFhmXe9KpaWHUZ_kr_PsoemhrdXNPVjZXp$> Add sessions hello world

File Changes

(1 file<https://urldefense.com/v3/__https:/github.com/mathomp4/MPITests/pull/1/files__;!!Bt8fGhp8LhKGRg!FwjK_Ds1tz4dAuHmk29pOSa3ScWBs882LDV0xbcBrQTlcsINGHrZBTPFhmXe9KpaWHUZ_kr_PsoemhrdXKj6QZ-0$>)

  *   A Sessions/helloWorld.mpi4.sessions.F90<https://urldefense.com/v3/__https:/github.com/mathomp4/MPITests/pull/1/files*diff-caaa3981b3701dcbfc8030a57fee363ff47864f90a76af8b37f82204b889c500__;Iw!!Bt8fGhp8LhKGRg!FwjK_Ds1tz4dAuHmk29pOSa3ScWBs882LDV0xbcBrQTlcsINGHrZBTPFhmXe9KpaWHUZ_kr_PsoemhrdXF0zVWIn$> (133)

Patch Links:

  *   https://github.com/mathomp4/MPITests/pull/1.patch<https://urldefense.com/v3/__https:/github.com/mathomp4/MPITests/pull/1.patch__;!!Bt8fGhp8LhKGRg!FwjK_Ds1tz4dAuHmk29pOSa3ScWBs882LDV0xbcBrQTlcsINGHrZBTPFhmXe9KpaWHUZ_kr_PsoemhrdXE7uyI5t$>
  *   https://github.com/mathomp4/MPITests/pull/1.diff<https://urldefense.com/v3/__https:/github.com/mathomp4/MPITests/pull/1.diff__;!!Bt8fGhp8LhKGRg!FwjK_Ds1tz4dAuHmk29pOSa3ScWBs882LDV0xbcBrQTlcsINGHrZBTPFhmXe9KpaWHUZ_kr_PsoemhrdXApl82rt$>

**Comment by mathomp4** [comment]
@hppritcha Thanks for looking at it. I know Sessions behavior, etc. is not finalized but hearing it was in Open MPI 5 now, I had to try it. 😄 

This was done on my MacBook. Next week I'll try it out on our cluster with Gnu and Intel. Maybe I'll see something new then. If so, I'll look for the ompi issue and comment there

**Comment by hppritcha** [comment]
what are the values of pset_len array when you first call ```MPI_Session_get_nth_pset```?

**Comment by mathomp4** [comment]
Aww. Looks like I can't test this out on our cluster:
```
--------------------------------------------------------------------------
Your application has invoked an MPI function that is not supported in
this environment.

  MPI function: MPI_Comm_from_group/MPI_Intercomm_from_groups
  Reason:       The PML being used - ucx - does not support MPI sessions related features
--------------------------------------------------------------------------
```

**Comment by hppritcha** [comment]
trying using OB1 PML -
```
export OMPI_MCA_pml=ob1
```

**Comment by mathomp4** [comment]
> what are the values of pset_len array when you first call `MPI_Session_get_nth_pset`?

@hppritcha Here is what I get:

```
[1,3]<stdout>:  Pset            0  length:           12
[1,3]<stdout>:  Pset            1  length:           11
[1,3]<stdout>:  Pset            2  length:           14
[1,1]<stdout>:  Pset            0  length:           12
[1,1]<stdout>:  Pset            1  length:           11
[1,1]<stdout>:  Pset            2  length:           14
[1,0]<stdout>:  Pset            0  length:           12
[1,0]<stdout>:  Pset            1  length:           11
[1,0]<stdout>:  Pset            2  length:           14
[1,2]<stdout>:  Pset            0  length:           12
[1,2]<stdout>:  Pset            1  length:           11
[1,2]<stdout>:  Pset            2  length:           14
```

**Comment by hppritcha** [comment]
you don't need to do more testing.  i found an issue with the fortran interface.

**Comment by mathomp4** [comment]
> you don't need to do more testing. i found an issue with the fortran interface.

Oh. yay!

But I will say that the ob1 pml did work:

```
$ mpirun -np 10 -npernode 1 --mca pml ob1 ./helloWorld.mpi4.sessions.exe
Compiler Version: Intel(R) Fortran Intel(R) 64 Compiler Classic for applications running on Intel(R) 64, Version 2021.6.0 Build 20220226_000000
MPI Version: 3.1
MPI Library Version: Open MPI v5.0.0, package: Open MPI mathomp4@discover32 Distribution, ident: 5.0.0, repo rev: v5.0.0, Oct 26, 2023
 Pset            0  name: mpi://WORLD
 Pset            1  name: mpi://SELF
 Pset            2  name: mpix://SHARED
Process    0 of   10 is on borgl079
Process    7 of   10 is on borgm058
Process    3 of   10 is on borgm039
Process    4 of   10 is on borgm040
Process    2 of   10 is on borgm038
Process    5 of   10 is on borgm042
Process    6 of   10 is on borgm057
Process    9 of   10 is on borgm061
Process    8 of   10 is on borgm059
Process    1 of   10 is on borgm037
```

Looks like we only get the WORLD, SELF, and SHARED psets even with multiple nodes. I was wondering if I'd get `node://borgm038` or the like, but nope. 😄

**Pull request merged**
